spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liaoxin0328
    url: jdbc:mysql://localhost:3306/miniai?useUnicode=true&characterEncoding=utf8
server:
  port: 8081
mybatis:
  mapper-locations: classpath:/mapper/*.xml
