spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liaoxin0328
    url: jdbc:mysql://localhost:3306/miniai?characterEncoding=utf8&useSSL=false

server:
  port: 8081
mybatis:
  mapper-locations: classpath:/mapper/*.xml


jwt:
  expire: 604800
  secret: 12345678
  header: Authorized

open:
  ai:
    request:
      timeout: 5000
    key:
