spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: @datasource.username@
    password: @datasource.password@
    url: @datasource.url@
server:
  port: 8081
mybatis:
  mapper-locations: classpath:/mapper/*.xml


jwt:
  expire: @jwt.expire@
  secret: @jwt.secret@
  header: @jwt.header@
